### ISSUE TITLE
Possibility to specify php version

### ISSUE THREAD

**Issue by gpasini** [ubient/laravel-vapor-action#10]
Hi,

Thanks for this github action.

Is it possible to specify the php version for the dockerfile ?

**Comment by claudiodekker** [comment]
Hello,

As you can see in the Dockerfile, it is "continuing" on top of [the Dockerfile that the people behind composer published (specifically, release 1.9.0](https://hub.docker.com/_/composer?tab=tags&page=1&name=1.9.0)): https://github.com/ubient/laravel-vapor-action/blob/f66f03dfba041d3da3705b4d689d282d5251383b/Dockerfile#L1

Because of that, we're dependent on [what PHP version they decided to use (see here)](https://github.com/composer/docker/blob/47c6a2cc73d7c2c5593f72ed62456d997236c71f/1.9/Dockerfile#L1), so there's not a lot you can do about this. As such, the short answer is that **it is not possible to specify the PHP version to use with this action**.

### However..
There is an option that _might_ work with a bit of luck, but it is quite difficult if you're not too familiar with Dockerfiles:

1. Fork this repository
2. Copy the contents of the [composer Dockerfile](https://github.com/ubient/laravel-vapor-action/blob/f66f03dfba041d3da3705b4d689d282d5251383b/Dockerfile)
3. Replace the 1st line ('from:...', see above) of our Dockerfile with the Dockerfile contents you copied at step 2.
4. Replace the "from: php" line at the top with the specific PHP version you need
5. Change the following in [the Action you configure](https://github.com/ubient/laravel-vapor-action#setting-up-our-github-action) and **hope for the best**:
```diff
-   - uses: ubient/laravel-vapor-action@master
+   - uses: user/your-forked-repository@branch
```

I hope this helps you!

**Comment by gpasini** [comment]
Sadly i'm not very familiar with Dockerfile so i will not try it

Thank you anyway for your reply

**Comment by claudiodekker** [comment]
Hi! I realize this issue has been closed for a while now, but I figured I'd still post an update in case anyone ever lands here via (for example) Google: 

**This is now supported in a fairly easy-to-use/copy-paste friendly way:** https://github.com/ubient/laravel-vapor-action#advanced-usage

Enjoy!
